apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: retailpulse
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"

  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: RetailPulse
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
