apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: retailpulse
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: retailpulse_app
        static_configs:
          - targets: ['streamlit:8000']
        metrics_path: /metrics
